#!/usr/bin/env bash

# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Add Nginx configuration to return "Hello World!" at the root location
sudo sh -c "echo 'server {
    listen 80;
    server_name localhost;

    location / {
        return 200 \"Hello World!\";
    }
}' > /etc/nginx/sites-available/hello-world"

sudo ln -s /etc/nginx/sites-available/hello-world /etc/nginx/sites-enabled/

# Restart Nginx to apply changes
sudo service nginx restart

