#!/usr/bin/env bash

if [ -x "$(command -v nginx)" ]; then
    echo "Nginx is already installed. Uninstalling and installing again..."
    apt-get -y remove nginx
    apt-get -y install nginx
else
    echo "Nginx is not installed. Installing now..."
    apt-get -y update
    apt-get -y install nginx
fi

